//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Deliverable24_Lab28_CreateWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public string Name { get; set; }
        public string Category { get; set; }
        public string Rating { get; set; }
        public string ImgSrc { get; set; }
    }
}
